version: "3.9"

services:
  fastapi:
    build: ./app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code
      - host=db
      - user=myuser
      - password=mypassword
      - database=mydatabase
      - JWT_SECRET_KEY=your_jwt_secret_here
      - JWT_REFRESH_SECRET_KEY=your_jwt_refresh_secret_here
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
